# Generated by Django 4.2.8 on 2023-12-11 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('startOfProduction', models.IntegerField()),
                ('endOfProduction', models.IntegerField()),
                ('engines', models.CharField(max_length=255)),
                ('bodyType', models.CharField(choices=[('sedan', 'Sedan'), ('kombi', 'Kombi'), ('hatchback', 'Hatchback'), ('cabriolet', 'Kabriolet'), ('coupe', 'Coupe')], default='sedan', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=255)),
                ('partOpis', models.CharField(max_length=1000)),
                ('samochod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samochod.samochod')),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
