# Generated by Django 4.2.8 on 2023-12-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochod', '0004_remove_part_samochod'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('oczekujace', 'Oczekujące'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='oczekujace', max_length=255),
        ),
    ]
